import {
  MessageEvent, FollowEvent, UnfollowEvent, JoinEvent, LeaveEvent, WebhookRequestBody
} from '@line/bot-sdk';

// Webhook event object which contains the sent message.
// https://developers.line.biz/en/reference/messaging-api/#message-event
export const textMessageEvent: MessageEvent = {
  replyToken: 'nHuyWiB7yP5Zw52FIkcQobQuGDXCTA',
  type: 'message',
  mode: 'active',
  timestamp: 1462629479859,
  source: {
    type: 'group',
    groupId: 'Ca56f94637cnrkd8F',
    userId: 'U4af49806uy29Jjei4n'
  },
  message: {
    id: '444573844083572737',
    type: 'text',
    text: '@All @example Good Morning!! (love)',
    emojis: [
      {
        index: 29,
        length: 6,
        productId: '5ac1bfd5040ab15980c9b435',
        emojiId: '001'
      }
    ],
    mention: {
      mentionees: [
        {
          index: 0,
          length: 4,
          userId: 'U49585cd50d5mrj6Rjd'
        },
        {
          index: 5,
          length: 8,
          userId: 'U49585cd0dg5kfds6jf'
        }
      ]
    }
  }
};

// Event object for when your LINE Official Account is added as a friend (or unblocked).
export const followEvent: FollowEvent = {
  replyToken: 'nHuyWiB7yP5Zw52FIkcQobQuGDXCTA',
  type: 'follow',
  mode: 'active',
  timestamp: 1462629479859,
  source: {
    type: 'user',
    userId: 'U4af498062984jFu4fd'
  }
};

// Event object for when your LINE Official Account is blocked.
export const unfollowEvent: UnfollowEvent = {
  type: 'unfollow',
  mode: 'active',
  timestamp: 1462629479859,
  source: {
    type: 'user',
    userId: 'U4af498frw0629Hu64H'
  }
};

// Event object for when your LINE Official Account joins a group chat or multi-person chat.
export const joinEvent: JoinEvent = {
  replyToken: 'nHuyWiB7yP5Zw52FIkcQobQuGDXCTA',
  type: 'join',
  mode: 'active',
  timestamp: 1462629479859,
  source: {
    type: 'group',
    groupId: 'C4af49806fs29jf5jks'
  }
};

// Event object for when a user removes your LINE Official Account from a group chat
// or when your LINE Official Account leaves a group chat or multi-person chat.
export const leaveEvent: LeaveEvent = {
  type: 'leave',
  mode: 'active',
  timestamp: 1462629479859,
  source: {
    type: 'group',
    groupId: 'C4af498d062953Hekl6'
  }
};

// JSON object containing events generated by the LINE platform.
export const webhookRequestCollection: WebhookRequestBody = {
  destination: 'dslfjdslkfjlsdf',
  events: [
    textMessageEvent,
    followEvent,
    unfollowEvent,
    joinEvent,
    leaveEvent
  ]
};
